services:
  postgres:
    image: postgres:17-alpine
    container_name: trade_postgres_db
    environment:
      POSTGRES_USER: tradeuser
      POSTGRES_PASSWORD: tradepassword
      POSTGRES_DB: tradedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    command:
      - "-c"
      - "maintenance_work_mem=4GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "checkpoint_timeout=1800s"
      - "-c"
      - "checkpoint_completion_target=0.9"


volumes:
  postgres_data:
